defmodule Mix.Tasks.RefactorTest do
  use ExUnit.Case, async: true

  alias Mix.Tasks.Refactor

  # These cover the `--auto` staging fix (#237): a file generated by a
  # refactor during `prepare/1` (e.g. ExtractSharedModule's `*.Shared`
  # host) lands on disk but isn't in the per-unit `paths` the auto-stager
  # knows about. Without picking up the working-tree delta it stays
  # untracked and gets re-created every fixpoint pass, so the run never
  # converges. `stage_paths/3` snapshots the tree before the unit and
  # stages exactly what appeared afterwards.

  describe "parse_porcelain/1" do
    test "extracts paths from untracked, modified and added entries" do
      output = """
      ?? lib/my_app/items/shared.ex
       M lib/my_app/items.ex
      A  lib/new_file.ex
      """

      assert Refactor.parse_porcelain(output) ==
               MapSet.new([
                 "lib/my_app/items/shared.ex",
                 "lib/my_app/items.ex",
                 "lib/new_file.ex"
               ])
    end

    test "keeps the destination path for renames" do
      output = "R  lib/old_name.ex -> lib/new_name.ex\n"

      assert Refactor.parse_porcelain(output) ==
               MapSet.new(["lib/new_name.ex"])
    end

    test "is empty for a clean tree" do
      assert Refactor.parse_porcelain("") == MapSet.new()
    end
  end

  describe "stage_paths/3 (real git repo)" do
    setup do
      repo =
        Path.join(System.tmp_dir!(), "refactor_stage_#{System.unique_integer([:positive])}")

      File.mkdir_p!(repo)
      git!(repo, ["init", "-q"])
      git!(repo, ["config", "user.email", "test@example.com"])
      git!(repo, ["config", "user.name", "Test"])

      File.write!(Path.join(repo, "a.ex"), "defmodule A do\nend\n")
      git!(repo, ["add", "a.ex"])
      git!(repo, ["commit", "-q", "-m", "init"])

      on_exit(fn -> File.rm_rf!(repo) end)
      {:ok, repo: repo}
    end

    test "stages a file the unit newly generated, in addition to the input paths", %{repo: repo} do
      # Baseline: tree is clean before the "refactor" runs.
      baseline = Refactor.git_porcelain_paths(repo)
      assert baseline == MapSet.new()

      # The unit modifies its input file *and* generates a brand new one
      # (the `*.Shared` host analogue) that no caller reported as touched.
      File.write!(Path.join(repo, "a.ex"), "defmodule A do\n  def x, do: 1\nend\n")
      File.write!(Path.join(repo, "shared.ex"), "defmodule Shared do\nend\n")

      staged = Refactor.stage_paths(["a.ex"], baseline, repo)

      assert "a.ex" in staged
      assert "shared.ex" in staged
    end

    test "ignores pre-existing dirty files that this unit did not create", %{repo: repo} do
      # A stray untracked file sits in the tree *before* the unit runs.
      File.write!(Path.join(repo, "stray.txt"), "not from the refactor\n")

      baseline = Refactor.git_porcelain_paths(repo)
      assert "stray.txt" in baseline

      # The unit only touches its input and generates one file.
      File.write!(Path.join(repo, "a.ex"), "defmodule A do\n  def x, do: 1\nend\n")
      File.write!(Path.join(repo, "shared.ex"), "defmodule Shared do\nend\n")

      staged = Refactor.stage_paths(["a.ex"], baseline, repo)

      assert "a.ex" in staged
      assert "shared.ex" in staged
      refute "stray.txt" in staged
    end

    test "after staging + commit, the generated file is tracked and the tree converges", %{
      repo: repo
    } do
      baseline = Refactor.git_porcelain_paths(repo)

      File.write!(Path.join(repo, "a.ex"), "defmodule A do\n  def x, do: 1\nend\n")
      File.write!(Path.join(repo, "shared.ex"), "defmodule Shared do\nend\n")

      staged = Refactor.stage_paths(["a.ex"], baseline, repo)
      git!(repo, ["add" | staged])
      git!(repo, ["commit", "-q", "-m", "extract shared"])

      # Convergence: the generated file is now tracked, so a clean tree
      # has no untracked `shared.ex` left to regenerate on the next pass.
      assert Refactor.git_porcelain_paths(repo) == MapSet.new()
      assert {_, 0} = System.cmd("git", ["ls-files", "--error-unmatch", "shared.ex"], cd: repo)
    end
  end

  defp git!(repo, args) do
    case System.cmd("git", args, cd: repo, stderr_to_stdout: true) do
      {_, 0} -> :ok
      {output, code} -> flunk("git #{Enum.join(args, " ")} failed (#{code}):\n#{output}")
    end
  end
end
